--- 
- hosts: all 
  become: true 
  tasks: 
    - name: create users 
      user: 
        name: "{{item.name}}"
        group: "{{item.group}}" 
      loop: 
        - {name: siva, group: root}
        - {name: arun, group: docker}

